config/routes.rb
Rails.application.routes.draw do

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :laboratories
  resources :analysis
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :user
  belongs_to :laboratory
  has_many :variants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  has_many :analysis
  validates :name, uniqueness:  true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :analysis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_commit :async_update, on: [:create, :update]

  private

  def async_update
    UpdateUserJob.perform_later(self)
  end
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :analysis
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :authenticate_user!
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]

  def index
    @analysis = Analysis.all
  end

  def new
    @analysis = Analysis.new
  end

  def create
    @analysis = Analysis.new(analysis_params)
    @analysis.user = current_user
    if @analysis.save
      redirect_to @analysis, notice: 'Created successfully!'
    else
      render :new
    end
  end

  def show
    @users = User.all
  end

  def edit
  end

  def update
    if @analysis.update(analysis_params)
      redirect_to analysis_path(@analysis), notice: 'Updated successfully!', status: :see_other
    else
      render :edit
    end
  end

  def destroy
    @analysis.destroy
    redirect_to analysis_index_url, notice: 'Analysis was successfully destroyed!', status: :see_other
  end


  private

  def set_analysis
    @analysis = Analysis.find(params[:id])
  end

  def analysis_params
    params.require(:analysis).permit(:id, :name, :type, :sample, :user_id, :username, :laboratory_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_laboratory, only: [:show, :edit, :update, :destroy]


  def index
    @laboratories = Laboratory.all
  end

  def show

  end

  def new
    @laboratory = Laboratory.new
  end

  def create
    @laboratory = Laboratory.new(laboratories_params)

    if @laboratory.save
      redirect_to laboratory_path(@laboratory), notice: 'Created successfully!'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @laboratory.update(laboratories_params)
      redirect_to laboratory_path(@laboratory), notice: 'Updated successfully!'
    else
      render :edit
    end
  end

  private
  def laboratories_params
    params.require(:laboratory).permit(:name, :location)
  end

  def set_laboratory
    @laboratory = Laboratory.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def update
    if current_user.update(user_params)
      UpdateUserJob.perform_later(current_user)  # <- The job is queued
      flash[:notice] = "Your profile has been updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:users).permit(:email, :username, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analysis/_form.html.erb
<%= simple_form_for(analysis, url: analysis_index_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="width: 1000px;">
    <%= f.input :name, placeholder: "Enter analysis name" %>
    <%# <%= f.input :type, placeholder: "Enter analysis" %>
    <%= f.input :sample, placeholder: "Sample" %>
    <%# <%= f.input :user_id, placeholder: "User" %>
    <%= f.input :laboratory_id, placeholder: "Laboratory" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/analysis/create.html.erb
<h1>Analysis#create</h1>
<p>Find me in app/views/analysis/create.html.erb</p>

app/views/analysis/destroy.html.erb
<h1>Analysis#destroy</h1>
<p>Find me in app/views/analysis/destroy.html.erb</p>

app/views/analysis/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Analysis#edit</h1>

      <%# <%= render "form", analysis: @analysis %>
      <%= simple_form_for(@analysis, url: analysis_path(@analysis), method: :put) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs" style="width: 1000px;">
          <%= f.input :name, placeholder: "Enter analysis name" %>
          <%# <%= f.input :type, placeholder: "Enter analysis" %>
          <%= f.input :sample, placeholder: "Sample" %>
          <%= f.input :user_id, placeholder: "User" %>
          <%= f.input :laboratory_id, placeholder: "Laboratory" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/analysis/index.html.erb
<div class="container">
  <h1 class="text-center mt-3">Welcome to your panel analysis!</h1>
  <div class="row mt-5">
    <div class="col-6">
      <ul>
        <% @analysis.each do |analyse| %>
          <li> ID-<%= analyse.id %>: <%= link_to analyse.name, analysis_path(analyse) %>
           (<%= analyse.sample %>)
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col">
      <div class="row">
        <div class="col d-flex align-items-center justify-content-center">
          <%= link_to "New Analysis", new_analysis_path, class: "btn-primary" %>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col d-flex align-items-center justify-content-center">
          <i class="fa-solid fa-arrow-up-wide-short fa-xl"></i>
        </div>

      </div>
    </div>


  </div>
  <div class="row">
    <div class="col d-flex justify-content-center">

      <h3 class="mt-5">
        <%= image_tag "group-medical.jpg", style: "width:100%;" %>
      </h3>

    </div>

  </div>

</div>

app/views/analysis/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Analysis#new</h1>

      <%= render "form", analysis: @analysis %>
    </div>
  </div>
</div>

app/views/analysis/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Analysis#show</h1>
      <h2><%= @analysis.name %></h2>
         <h2><%= @users.find(@analysis.user_id).username %></h2>

      <div class="button-container">
        <%= link_to "Back to Analysis", analysis_index_path, class: "btn-primary" %>
        <%= link_to "Edit", edit_analysis_path(@analysis), class: "btn-primary" %>
        <%= button_to 'Destroy', @analysis, class: "btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
  </div>
</div>

app/views/analysis/update.html.erb
<h1>Analysis#update</h1>
<p>Find me in app/views/analysis/update.html.erb</p>

app/views/laboratories/_form.html.erb
<%= simple_form_for(laboratory, url: laboratories_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="width: 1000px;">
    <%= f.input :name, placeholder: "Enter Laboratory name" %>
    <%= f.input :location, placeholder: "Location" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/laboratories/create.html.erb
<h1>Laboratories#create</h1>
<p>Find me in app/views/laboratories/create.html.erb</p>

app/views/laboratories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Laboratories#edit</h1>
      <p>Find me in app/views/laboratories/edit.html.erb</p>

      <%= simple_form_for(@laboratory, url: laboratory_path(@laboratory), method: :put) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs" style="width: 75%;">
          <%= f.input :name, placeholder: "Enter Laboratory name" %>
          <%= f.input :location, placeholder: "Location" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/laboratories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Laboratories#index</h1>
      <ul>
        <% @laboratories.each do |laboratory| %>
          <li> <%= link_to laboratory.name, laboratory_path(laboratory) %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/laboratories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Laboratories#new</h1>

      <%= render "form", laboratory: @laboratory %>


    </div>
  </div>
</div>

app/views/laboratories/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-6 lab-info">
      <h1><%= @laboratory.name %></h1>
      <p><%= @laboratory.location %></p>
      <%= link_to "Edit", edit_laboratory_path(@laboratory), class: "btn-primary" %>

    </div>
    <div class="col-6">
      <%= image_tag "sante-medecine.jpeg", class: "lab-image img-fluid", alt: "Laboratory Image" %>
    </div>
  </div>
</div>

app/views/laboratories/update.html.erb
<h1>Laboratories#update</h1>
<p>Find me in app/views/laboratories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GenoScreen | Manage Your Genetics Data Analysis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>GenoScreen helps you manage your genetic data!</h1>
    <%# <p>Brings your analysis to the next level.</p> %>
    <p><span data-controller="typed-js"></span></p>
    <%= link_to "Test it now", analysis_index_path, class: "btn-primary" %>
  </div>
</div>

<div class="container mt-5 mb-5">
  <h2 class="text-center"> How it works</h2>
  <div class="cards">
    <div class="card">
      <%= image_tag "apply.svg", alt: "Apply" %>
      <h4 class="mt-7">Apply</h4>
      <p>Apply your first analysis.</p>
    </div>
    <div class="card">
      <%= image_tag "learn.svg", alt: "Analyze" %>
      <h4>Analyze</h4>
      <p>Analyze your data.</p>
    </div>
    <div class="card">
      <%= image_tag "product.svg", alt: "Discover" %>
      <h4>Discover</h4>
      <p>Discover new insights.</p>
    </div>
  </div>
</div>

<div class="footer">
  <div class="links">
    <div class="link">
      <a href="#">
        <i class="fab fa-fw fa-facebook-f"></i>
      </a>
      <a href="#"><i class="fab fa-fw fa-github"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
    </div>
  </div>
  <%# <p>
    This website was code with
    <i class="fas fa-heart"></i>
  </p> %>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Laboratories", laboratories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Lab", new_laboratory_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Analysis", analysis_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Analysis", new_analysis_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "avatar.jpeg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>